@echo off
rem generated by setup.cmd - launches 3ds Max with the FlatCraft startup script
start "" "C:\Program Files\Autodesk\3ds Max 2024\3dsmax.exe" -U MAXScript "D:\FlatCraft\launcher\FC_Startup.ms"
