@echo off
rem FlatCraft launcher setup:
rem   1) finds 3ds Max, writes launch.cmd
rem   2) registers the flatcraft:// protocol for the current user (no admin)
rem Run once (double-click). Re-run after moving the folder or reinstalling Max.
setlocal
set "ROOT=%~dp0.."
for %%I in ("%ROOT%") do set "ROOT=%%~fI"

rem Preference order: 2024 first - the project's working version. Scenes saved
rem by a newer Max cannot be opened in 2024, so the first match wins here.
set "MAX="
for %%Y in (2024 2025 2026 2027 2023 2022 2021) do (
  if not defined MAX if exist "C:\Program Files\Autodesk\3ds Max %%Y\3dsmax.exe" set "MAX=C:\Program Files\Autodesk\3ds Max %%Y\3dsmax.exe"
)
if not defined MAX (
  echo [FlatCraft] 3ds Max not found in "C:\Program Files\Autodesk\" - edit this file manually.
  timeout /t 15 >nul 2>&1
  exit /b 1
)

> "%~dp0launch.cmd" (
  echo @echo off
  echo rem generated by setup.cmd - launches 3ds Max with the FlatCraft startup script
  echo start "" "%MAX%" -U MAXScript "%ROOT%\launcher\FC_Startup.ms"
)

reg add "HKCU\Software\Classes\flatcraft" /ve /d "URL:FlatCraft" /f >nul
reg add "HKCU\Software\Classes\flatcraft" /v "URL Protocol" /d "" /f >nul
reg add "HKCU\Software\Classes\flatcraft\shell\open\command" /ve /d "\"%~dp0launch.cmd\" \"%%1\"" /f >nul

echo [FlatCraft] OK: flatcraft:// registered. 3ds Max: %MAX%
timeout /t 5 >nul 2>&1
exit /b 0
